name: Decode gradle-wrapper.jar from base64

on:
  workflow_dispatch:

jobs:
  decode-wrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Decode gradle-wrapper.jar
        run: |
          mkdir -p gradle/wrapper
          base64 -d gradle/wrapper/gradle-wrapper.jar.base64 > gradle/wrapper/gradle-wrapper.jar

      - name: Commit decoded jar
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull origin main --rebase || true
          git add gradle/wrapper/gradle-wrapper.jar
          git commit -m "Restore gradle-wrapper.jar from base64" || echo "No changes to commit"
          git push origin main
