name: Build Kiss2Go APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.java'
      - '**.kt'
      - '**.xml'
      - 'build.gradle'
      - 'settings.gradle'
      - 'gradle/wrapper/gradle-wrapper.jar.base64'
      - '.github/workflows/android.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Decode gradle-wrapper.jar from base64
        run: |
          mkdir -p gradle/wrapper
          base64 -d gradle/wrapper/gradle-wrapper.jar.base64 > gradle/wrapper/gradle-wrapper.jar

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kiss2Go-APK
          path: app/build/outputs/apk/debug/app-debug.apk
