name: Build Kiss2Go APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Gradlew Rights
        run: chmod +x gradlew

      - name: Use Gradle Wrapper directly
  run: |
    ./gradlew wrapper
    chmod +x gradlew
    ./gradlew assembleDebug

      - name: Upload APK as GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Kiss2Go-Release
          tag_name: kiss2go-${{ github.run_number }}
          files: app/build/outputs/apk/debug/app-debug.apk
